# add this to the main compose file if you want to run homepage together with the media suite

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${SERVICE_HOSTNAME}:8057,localhost:8057  # add any domains if you need
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8057:3000
    restart: unless-stopped
