server_url: https://headscale.tomasvana.dev
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

tls_cert_path: ""
tls_key_path: ""

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

policy:
  path: /etc/headscale/acl.json
  mode: file

dns:
  magic_dns: true
  base_domain: tail.tomasvana.dev
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1

log:
  level: info
